### PR TITLE
add general paths

### PR DESCRIPTION
**Pull request by hpstuff**
Since just adding the baseUrl you can directly call absolute paths instead of relative I get all first level folder and files and add them to the paths so they can be resolved.

### CODE REVIEW

**Comment by jonkwheeler** [comment]
@hpstuff can you explain this a bit more? What is this solving / improving?

**Comment by hpstuff** [comment]
@jonkwheeler yeah sure, this is resolving the case in witch you don't have any specific paths in your tsconfig like in this example https://www.typescriptlang.org/tsconfig#baseUrl

**Comment by jonkwheeler** [comment]
Ah, I see. Okay. Gimme a bit and I'll PR this for you.

**Comment by hpstuff** [comment]
Oh really, that's cool I think you would like it.
Take your time if there is something that you want me to change I'm happy to.

**Comment by jonkwheeler** [comment]
I ran into an error immediately running this on my repos :/ Will have to debug.

**Comment by jonkwheeler** [comment]
Hey man, I think this is fix with https://github.com/jonkwheeler/tsconfig-replace-paths/pull/16

**Pull request closed without merging**
