### PR TITLE
Adds quiet option

### PR DESCRIPTION
**Pull request by steveruizok**
This PR adds a `-q --quiet` option to suppress console logs. If a user provides both quiet and verbose flags, the verbose flag will win.

### CODE REVIEW

**Comment by steveruizok** [comment]
Added an example project for testing the CLI.

```bash
cd example
yarn build
yarn build -q
yarn build -v
```

**Comment by steveruizok** [comment]
Added a `files` option to the package.json to prevent publishing the `src` folder.

**Comment by jonkwheeler** [comment]
Make sure to get the [README options](https://github.com/steveruizok/tsconfig-replace-paths/tree/patch-1#options) updated.

**Comment by jonkwheeler** [comment]
I don't want `examples/tsconfig.types.cjs.json` and `examples/tsconfig.types.esm.json` erased as they are what a user would need to export a package with both CommonJs and ESM. This is explained [here on the README](https://github.com/jonkwheeler/tsconfig-replace-paths#what-if-you-want-to-build-only-the-types).

**Comment by jonkwheeler** [comment]
Give me a bit here and I'll test this out. Thanks!

**Pull request closed without merging**
